docs: confluence document migration
frmscoe/rule-cli pull request #4
Opened 2024-05-10 12:56 UTC by curlyreeve

2024-05-13 05:19 UTC, Justus-at-Tazama requested changes

2024-05-13 05:19 UTC, Justus-at-Tazama commented on Images/image-20240125-060057.png
Folder should be lower-case which is why it's not rendering in the readme file.

2024-05-13 05:20 UTC, Justus-at-Tazama requested changes

2024-05-13 05:20 UTC, Justus-at-Tazama commented on README.md
> +r# Rule Command Line Interface Documentation
The heading # is prefaced with an errant 'r' which is why the heading doesn't render properly

2024-05-17 08:04 UTC, Sandy-at-Tazama requested changes
Image does not render

2024-05-17 08:06 UTC, Sandy-at-Tazama requested changes
This images folder is capitalised `Images`

2024-05-18 09:46 UTC, RobReeveLexTego submitted a review, later dismissed

2024-05-19 15:34 UTC, Sandy-at-Tazama submitted a review, later dismissed

2024-05-22 17:09 UTC, RobReeveLexTego submitted a review, later dismissed
image now in images, and not Images
file now called readme.md and not README.md

2024-05-23 09:29 UTC, Sandy-at-Tazama commented
@RobReeveLexTego  File still called README.md when I checked it now?

2024-05-23 09:32 UTC, RobReeveLexTego commented
<img width="395" alt="image" src="https://github.com/frmscoe/rule-cli/assets/77055177/17606d30-4d11-42b7-95a2-f5266c49c7ed">
Note the commit @Sandy-at-Tazama  - this is one of those horrible windows / linux issues

2024-05-23 09:47 UTC, Justus-at-Tazama commented
> image now in images, and not Images file now called readme.md and not README.md

Hi,

The all-caps README.md is the standard for GitHub and all of our repositories. Please retain the all-caps name?

2024-05-23 10:48 UTC, curlyreeve commented
Updated and done

2024-05-23 12:24 UTC, Sandy-at-Tazama approved these changes

2024-05-27 13:58 UTC, Justus-at-Tazama approved these changes

2024-05-27 13:58 UTC, merged